### ISSUE TITLE
[Suggestion] Option to use timers relative to boss phase

### ISSUE THREAD

**Issue by Spectre93** [j3rrr/ZeroNotes#4]
Hey, as a RL I love your addon and I have a suggestion to add some functionality I think would be nice to have.

As you know, your addon works incredibly well with bosses that phase on a set timer.  However, if the bosses phases at a variable time, then the later timers become more and more inaccurate.

ERT has some [not-so-well documented features](https://www.reddit.com/r/CompetitiveWoW/comments/jr29s7/help_ert_notes_activation_on_boss_spell_casts/) on starting timers based on the following events:
-SPELL_CAST_START
-SPELL_CAST_SUCCESS
-SPELL_AURA_APPLIED
-SPELL_AURA_REMOVED

**My suggestion** is to add an option to configure phase transitions in this way.
Example: When Artificer Xy'mox in Castle Nathria phases to Phase 2, she casts [Root of Extinction](https://www.wowhead.com/spell=329770/root-of-extinction). Her timers for her Phase 2 abilities start from that moment. Say you want to use a cooldown 30 seconds into that phase, you could write it like this in ERT:

```{time:0:30,SCS:329770:1} ```

SCS being Spell Cast Start, 329770 being the spell id, and 1 being the first occurence of the cast. The 30 seconds will start counting down right when her cast of Root of Extinction starts.

Of course you can't suggest a cooldown rotation based on relative timers, so you would still need to fill in an expected (or minimum) time for the phase duration, but by doing the timers like this they can be more accurate for the later phases on bosses that don't transition on a set timer.

Thank you for your time :)

**Comment by j3rrr** [comment]
Hi,

we know about that feature and already looked into that, but as you said, you can't suggest a cooldown rotation on relative timers.

Our Addon is not a tool to "write notes", it is exactly what you said, a tool to assign cooldowns.
Therefore you will always need to adjust timers based on your groups dps etc for non-scripted encounters.

The "magic" happens, when creating the note with your templates, not on the fly during an encounter, which would be necessary for your suggestion.

If you use our Note Display Weakaura, you can send the note with "Count Mode" enabled. This will replace the timer in the note with counter for each occurence of the the spell and grey out the line if the spell was cast once, twice, etc. 

That kind of eliminates the problem of non accurate timers and will most likely still won't get you in a situation where the suggested cooldown is not available, because timers will typically only be off by a few seconds which won't interfere the cooldown rotation.

**Comment by Spectre93** [comment]
You are absolutely right, I will try out the Weakaura and count mode, thanks!
